layout_spectrum: 0.2676449853461236
typography_spectrum: 0.5985355565790087
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.4974293918348849
  lightness: 0.6700729934964329
  saturation: 0.3042946110945195
  rhythmicContrast: 0.5469531053677201
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Tea and Cake
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact Us
    id: 8ee2088f-1aeb-4197-903f-ff5a20a32012
    type: content
favicon: null
title: Well why not share likes and alike with the world!
purpose: []
