name: Tea and Cake
favicon: null
layout_spectrum: 0.7536896835081279
typography_spectrum: 0.010850576218217611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8148145051673055
  lightness: 0.9204874637071043
  saturation: 0.5948627055622637
  rhythmicContrast: 0.3740921171847731
purpose: []
