name: Tea and Cake
favicon: null
layout_spectrum: 0.08124
typography_spectrum: 0.24399
title: Well why not share likes and alike with the world!
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#091009'
    - '#fdff00'
    - '#d9181b'
    - '#787379'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
